### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by daisukeXIV** [daisukeXIV/furima-40724#21]
# RenderURL
https://furima-40724.onrender.com/

# 出品用アカウント
## mail
seller@mail
## pass
seller1

# 購入用アカウント
## mail
buyer@mail
## pass
buyer1

**Comment by daisukeXIV** [comment]
# Basic認証
## ユーザー名
adimn
## pass
techcamp

**Comment by maimai0401** [comment]
最終課題「FURIMA」の開発、お疲れ様です!

ご提出いただいたアプリケーションについて、正常に動作することを確認いたしました。
達成要件を満たしましたので、LGTMとさせていただきます！おめでとうございます！

_※ Github上の最終課題の履歴はここまで頑張ってきたことの証となります。削除せず大切に保管するようにしましょう。_
